version: '3.8'

services:
  db:
    image: postgres:18
    container_name: fintrack-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance-tracker
    ports:
      - "5432:5432"
    volumes:
      - fintrack_pgdata:/var/lib/postgresql

volumes:
  fintrack_pgdata:
